[project]
name = "canalbox-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=37.5.3",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.7",
    "python-dateutil>=2.9.0.post0",
]
